apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
data:
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "STG-EKS-ACRLI",
            "metrics_collection_interval": 60
          },
          "container": {
            "metrics_collection_interval": 60,
            "namespace": ["acrli-daya-test","dayatest"],   # include test namespace
            "container_names": ["acr-li-b-test","ubuntu-stress"]  # include stress pod
          }
        },
        "force_flush_interval": 5
      }
    }