apiVersion: v1
kind: Namespace
metadata:
  name: dayatest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  namespace: dayatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: stress-ng
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "Starting CPU spike for 2 minutes...";
              stress-ng --cpu 2 --timeout 120s --metrics-brief;
              echo "Spike finished, sleeping 2 minutes...";
              sleep 120;
            done
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        readinessProbe:
          exec:
            command: ["sh", "-c", "echo ready"]  # simple probe to ensure pod becomes READY
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          exec:
            command: ["sh", "-c", "pgrep stress-ng || exit 1"]
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3